# Window settings
WIDTH = 1000
HEIGHT = 1000

# Ball settings
BALL_DIAMETER = 20
INITIAL_BALL_X = WIDTH // 2
INITIAL_BALL_Y = HEIGHT // 2
INITIAL_X_SPEED = -5
INITIAL_Y_SPEED = -8

# Paddle settings
PADDLE_WIDTH = 200
PADDLE_HEIGHT = 50
PADDLE_Y = 800
INITIAL_PADDLE_X = WIDTH // 2

# Wall settings
WALL_WIDTH = 20
WALL_HEIGHT = HEIGHT
FIRST_WALL_X = 0
SECOND_WALL_X = WIDTH - WALL_WIDTH
CEILING_Y = 0

# Blocks settings
BLOCKS_LOWER_LIMIT = 100
BLOCKS_UPPER_LIMIT = 200
